// This file is automatically generated
// Run "go run cmd/gen/gen.go" to update the list.

package publicsuffix

const defaultListVersion = "PSL version 011f11 (Sat Jun 27 17:01:45 2020)"

func DefaultRules() [1]Rule {
	return r
}

var r = [1]Rule{
	{1, "500: Internal Server Error", 1, false},
}

func init() {
	for i := range r {
		DefaultList.AddRule(&r[i])
	}
}
